apiVersion: batch/v1
kind: Job
metadata:
  name: generate-embeddings-reprod
  labels:
    app: imprinting
spec:
  template:
    metadata:
      labels:
        app: imprinting
    spec:
      priorityClassName: normal
      containers:
        - name: imprinting
          image: registry.datexis.com/jwesterhoff/imprinting:latest
          imagePullPolicy: Always # to force pulling the newest image
          command: ["python", "scripts/generate_embeddings.py"]
          env:
            - name: LANG
              value: 'C.UTF-8'
            - name: PYTHONUNBUFFERED
              value: '1'
            - name: IMAGENET_URL_DEVKIT_T_1_2
              valueFrom:
                secretKeyRef:
                  name: imagenet-url-devkit-t-1-2
                  key: IMAGENET_URL_DEVKIT_T_1_2
            - name: IMAGENET_URL_TRAIN_T_1_2
              valueFrom:
                secretKeyRef:
                  name: imagenet-url-train-t-1-2
                  key: IMAGENET_URL_TRAIN_T_1_2
            - name: IMAGENET_URL_VAL_T_ALL
              valueFrom:
                secretKeyRef:
                  name: imagenet-url-val-t-all
                  key: IMAGENET_URL_VAL_T_ALL
          resources:
            requests:
              cpu: "8"
            limits:
              nvidia.com/gpu: "1" # not sure if even 0 would work here
              memory: "64Gi"
          volumeMounts:
            - name: imprinting-reproduce-pvc
              mountPath: /app/imprinting-reproduce
            - name: imagenet-data-pvc
              mountPath: /app/imagenet-data
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: gpu
                    operator: In
                    values:
                      # - p100
                      # - k80
                      # - v100
                      - a100
                  # - key: cpuclass
                  #   operator: In
                  #   values:
                  #     - epyc
      volumes:
        - name: imprinting-reproduce-pvc
          persistentVolumeClaim:
            claimName: imprinting-reproduce-pvc
        - name: imagenet-data-pvc
          persistentVolumeClaim:
            claimName: imagenet-data-pvc
      imagePullSecrets:
        - name: private-registry-auth
      restartPolicy: Never
  backoffLimit: 1

# NOTES:
# - to build, run docker build -t registry.datexis.com/jwesterhoff/imprinting:latest . --platform=linux/amd64
# - to push, run docker push registry.datexis.com/jwesterhoff/imprinting:latest
# - to set the above secret keys and have them available in python env, do, e.g.,
#   `kubectl create secret generic kaggle-key --from-literal=KAGGLE_KEY='123'
# - tqdm and k9s: Run `kubectl attach <pod-name>` to see the progress of the job
#   nicely in the terminal (works well with tqdm unlike `kubectl log`)
