apiVersion: batch/v1
kind: Job
metadata:
  name: generate-embeddings-reprod
  labels:
    app: multi-imprinting
spec:
  template:
    metadata:
      labels:
        app: multi-imprinting
    spec:
      priorityClassName: normal
      containers:
        - name: multi-imprinting
          image: registry.datexis.com/jwesterhoff/multi-imprinting:latest
          command: ["python", "scripts/generate_embeddings.py"]
          env:
            - name: LANG
              value: 'C.UTF-8'
            - name: PYTHONUNBUFFERED
              value: '1'
            - name: IMAGENET_URL_DEVKIT_T_1_2
              valueFrom:
                secretKeyRef:
                  name: imagenet-url-devkit-t-1-2
                  key: IMAGENET_URL_DEVKIT_T_1_2
            - name: IMAGENET_URL_TRAIN_T_1_2
              valueFrom:
                secretKeyRef:
                  name: imagenet-url-train-t-1-2
                  key: IMAGENET_URL_TRAIN_T_1_2
            - name: IMAGENET_URL_VAL_T_ALL
              valueFrom:
                secretKeyRef:
                  name: imagenet-url-val-t-all
                  key: IMAGENET_URL_VAL_T_ALL
          resources:
            requests:
              cpu: "8"
            limits:
              nvidia.com/gpu: "1" # not sure if even 0 would work here
              memory: "64Gi"
          volumeMounts:
            - name: imprinting-reproduce-pvc
              mountPath: /app/imprinting-reproduce
            - name: imagenet-data-pvc
              mountPath: /app/imagenet-data
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: gpu
                    operator: In
                    values:
                      # - p100
                      # - k80
                      # - v100
                      - a100
                  # - key: cpuclass
                  #   operator: In
                  #   values:
                  #     - epyc
      volumes:
        - name: imprinting-reproduce-pvc
          persistentVolumeClaim:
            claimName: imprinting-reproduce-pvc
        - name: imagenet-data-pvc
          persistentVolumeClaim:
            claimName: imagenet-data-pvc
      imagePullSecrets:
        - name: private-registry-auth
      restartPolicy: Never

# NOTES:
# - To set the above secret keys and have them available in python env, do, e.g.,
#   `kubectl create secret generic kaggle-key --from-literal=KAGGLE_KEY='123'
# - tqdm and k9s: Run `kubectl attach <pod-name>` to see the progress of the job
#   nicely in the terminal (works well with tqdm unlike `kubectl log`)

# Resulting print from successfully running this job:
# │ +--------------+-------+-----------+----------------------+-----------+------------+------------+--------------+------+--------------+                                                                                                            │
# │ | Dataset      | Train | # Samples | Raw Image Resolution |  Location | Model Name | Embeddings | # Embeddings | Dim. | Duration (s) |                                                                                                            │
# │ +--------------+-------+-----------+----------------------+-----------+------------+------------+--------------+------+--------------+                                                                                                            │
# │ | CIFAR10      | test  |   10000   |     32x32 (RGB)      | From Disk |  resnet18  | From Disk  |    10000     | 512  |         0    |                                                                                                            │
# │ | CIFAR10      | train |   50000   |     32x32 (RGB)      | From Disk |  resnet18  | From Disk  |    50000     | 512  |         0    |                                                                                                            │
# │ | CIFAR10      | test  |   10000   |     32x32 (RGB)      | From Disk |  resnet50  | From Disk  |    10000     | 2048 |         0    |                                                                                                            │
# │ | CIFAR10      | train |   50000   |     32x32 (RGB)      | From Disk |  resnet50  | From Disk  |    50000     | 2048 |         0    |                                                                                                            │
# │ | CIFAR10      | test  |   10000   |     32x32 (RGB)      | From Disk |  vit_b_16  | From Disk  |    10000     | 768  |         0    |                                                                                                            │
# │ | CIFAR10      | train |   50000   |     32x32 (RGB)      | From Disk |  vit_b_16  | From Disk  |    50000     | 768  |         0    |                                                                                                            │
# │ | CIFAR10      | test  |   10000   |     32x32 (RGB)      | From Disk |   swin_b   | From Disk  |    10000     | 1024 |         0    |                                                                                                            │
# │ | CIFAR10      | train |   50000   |     32x32 (RGB)      | From Disk |   swin_b   | From Disk  |    50000     | 1024 |         0    |                                                                                                            │
# │ +--------------+-------+-----------+----------------------+-----------+------------+------------+--------------+------+--------------+                                                                                                            │
# │ | FashionMNIST | test  |   10000   |      28x28 (L)       | From Disk |  resnet18  | From Disk  |    10000     | 512  |         0    |                                                                                                            │
# │ | FashionMNIST | train |   60000   |      28x28 (L)       | From Disk |  resnet18  | From Disk  |    60000     | 512  |         0    |                                                                                                            │
# │ | FashionMNIST | test  |   10000   |      28x28 (L)       | From Disk |  resnet50  | From Disk  |    10000     | 2048 |         0    |                                                                                                            │
# │ | FashionMNIST | train |   60000   |      28x28 (L)       | From Disk |  resnet50  | From Disk  |    60000     | 2048 |         0    |                                                                                                            │
# │ | FashionMNIST | test  |   10000   |      28x28 (L)       | From Disk |  vit_b_16  | From Disk  |    10000     | 768  |         0    |                                                                                                            │
# │ | FashionMNIST | train |   60000   |      28x28 (L)       | From Disk |  vit_b_16  | From Disk  |    60000     | 768  |         0    |                                                                                                            │
# │ | FashionMNIST | test  |   10000   |      28x28 (L)       | From Disk |   swin_b   | From Disk  |    10000     | 1024 |         0    |                                                                                                            │
# │ | FashionMNIST | train |   60000   |      28x28 (L)       | From Disk |   swin_b   | From Disk  |    60000     | 1024 |         0    |                                                                                                            │
# │ +--------------+-------+-----------+----------------------+-----------+------------+------------+--------------+------+--------------+                                                                                                            │
# │ | MNIST        | test  |   10000   |      28x28 (L)       | From Disk |  resnet18  | From Disk  |    10000     | 512  |         0    |                                                                                                            │
# │ | MNIST        | train |   60000   |      28x28 (L)       | From Disk |  resnet18  | From Disk  |    60000     | 512  |         0    |                                                                                                            │
# │ | MNIST        | test  |   10000   |      28x28 (L)       | From Disk |  resnet50  | From Disk  |    10000     | 2048 |         0    |                                                                                                            │
# │ | MNIST        | train |   60000   |      28x28 (L)       | From Disk |  resnet50  | From Disk  |    60000     | 2048 |         0    |                                                                                                            │
# │ | MNIST        | test  |   10000   |      28x28 (L)       | From Disk |  vit_b_16  | From Disk  |    10000     | 768  |         0    |                                                                                                            │
# │ | MNIST        | train |   60000   |      28x28 (L)       | From Disk |  vit_b_16  | From Disk  |    60000     | 768  |         0    |                                                                                                            │
# │ | MNIST        | test  |   10000   |      28x28 (L)       | From Disk |   swin_b   | From Disk  |    10000     | 1024 |         0    |                                                                                                            │
# │ | MNIST        | train |   60000   |      28x28 (L)       | From Disk |   swin_b   | From Disk  |    60000     | 1024 |         0    |                                                                                                            │
# │ +--------------+-------+-----------+----------------------+-----------+------------+------------+--------------+------+--------------+                                                                                                            │
# │ | ImageNet     | val   |   50000   |    500x375 (RGB)     | From Disk |  resnet18  | Extracted  |     7250     | 512  |      2757    |                                                                                                            │
# │ | ImageNet     | train |  1281167  |    250x250 (RGB)     | From Disk |  resnet18  | Extracted  |    186576    | 512  |     68639    |                                                                                                            │
# │ | ImageNet     | val   |   50000   |    500x375 (RGB)     | From Disk |  resnet50  | Extracted  |     7250     | 2048 |      2345    |                                                                                                            │
# │ | ImageNet     | train |  1281167  |    250x250 (RGB)     | From Disk |  resnet50  | Extracted  |    186576    | 2048 |     58474    |                                                                                                            │
# │ | ImageNet     | val   |   50000   |    500x375 (RGB)     | From Disk |  vit_b_16  | Extracted  |     7250     | 768  |      2386    |                                                                                                            │
# │ | ImageNet     | train |  1281167  |    250x250 (RGB)     | From Disk |  vit_b_16  | Extracted  |    186576    | 768  |     64979    |                                                                                                            │
# │ | ImageNet     | val   |   50000   |    500x375 (RGB)     | From Disk |   swin_b   | Extracted  |     7250     | 1024 |      2596    |                                                                                                            │
# │ | ImageNet     | train |  1281167  |    250x250 (RGB)     | From Disk |   swin_b   | Extracted  |    186576    | 1024 |     62648    |                                                                                                            │
# │ +--------------+-------+-----------+----------------------+-----------+------------+------------+--------------+------+--------------+                                                                                                            │
# │ +--------------+-------+-----------+----------------------+-----------+------------+------------+--------------+------+--------------+
