apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imagenet-data-reproduce-pvc
spec:
  storageClassName: shared
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Gi
