apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imprinting-reproduce-pvc
spec:
  storageClassName: shared
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
