{
    "backbones": ["resnet18", "resnet50", "vit_b_16", "swin_b", "convnextv2-femto-1k-224"],
    "datasets": [["MNIST", "MNIST-M", "USPS", "SVHN"]],
    "label_remappings": {
        "combined": {0: 0, 10: 0, 20: 0, 30: 0, 1: 1, 11: 1, 21: 1, 31: 1, 2: 2, 12: 2, 22: 2, 32: 2, 3: 3, 13: 3, 23: 3, 33: 3, 4: 4, 14: 4, 24: 4, 34: 4, 5: 5, 15: 5, 25: 5, 35: 5, 6: 6, 16: 6, 26: 6, 36: 6, 7: 7, 17: 7, 27: 7, 37: 7, 8: 8, 18: 8, 28: 8, 38: 8, 9: 9, 19: 9, 29: 9, 39: 9},
    },
    "task_splits": {
        "all": [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],
    },
    "seeds": [
        17121997,
        123987,
        12412312
    ],
    "normalize_input_data": [
        "l2"
    ],
    "normalize_for_proxy_selection": [
        "none",
        "l2"
    ],
    "presampling_methods": [
        "all"
    ],
    "presampling_quantiles_values": [
        [0, 1.0]
    ],
    "presampling_fewshot_values": [
        -1
    ],
    "proxy_methods": [
        "kmeans",
    ],
    "ks": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15
    ],
    "normalize_weights": [
        "l2"
    ],
    "aggregation_methods": [
        "max"
    ],
    "ms": [
        -1,
    ]
}
