{
    "backbones": ["resnet18"],
    "datasets": [["MNIST"]],
    "label_remappings": {
        "none": {}
    },
    "task_splits": {
        "short": [[0, 1, 2]]
    },
    "seeds": [
        17121997,
    ],
    "normalize_input_data": [
        "l2"
    ],
    "normalize_for_proxy_selection": [
        "none",
    ],
    "normalize_layer_activations": [
        "l2",
    ],
    "presampling_methods": [
        "all",
    ],
    "presampling_quantiles_values": [
        [0, 1.0],
    ],
    "presampling_fewshot_values": [
        -1,
    ],
    "proxy_methods": [
        "kmeans",
    ],
    "ks": [
        3,
    ],
    "normalize_weights": [
        "l2",
    ],
    "aggregation_methods": [
        "max",
    ],
    "ms": [
        -1,
    ]
}
