{
    "backbones": ["resnet18", "resnet50", "vit_b_16", "swin_b", "convnextv2-femto-1k-224"],
    "datasets": [["MNIST"], ["FashionMNIST"], ["CIFAR10"]],
    "label_remappings": {
        "none": {}
    },
    "task_splits": {
        "all": [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],
    },
    "seeds": [
        14057,
        994348,
        23092007,
        123456,
        98765
    ],
    "normalize_input_data": [
        "l2"
    ],
    "normalize_for_proxy_selection": [
        "l2"
    ],
    "presampling_methods": [
        "all",
    ],
    "presampling_quantiles_values": [
        [0, 1.0],
    ],
    "presampling_fewshot_values": [
        -1,
        1,
        2,
        5,
        10,
        20,
        50,
        100,
        200,
        400,
        600,
        800,
        1000,
    ],
    "proxy_methods": [
        "kmeans",
    ],
    "ks": [
        -1,
        1,
        5,
        20
    ],
    "normalize_weights": [
        "l2",
    ],
    "aggregation_methods": [
        "max",
    ],
    "ms": [
        -1,
    ]
}
